defaults:
  - override hydra/job_logging: disabled
  - _self_

seed: 0

environment:
  id: ALE/Pong-v5
  frame_stack: 4
  frame_skip: 4
  screen_size: 96
  max_episode_steps: 3000

self_play:
  worker_iterations: 1
  num_envs: 4
  steps_per_iteration: 400
  num_simulations: 50
  add_exploration_noise: false
  temperature: 1.0

replay:
  max_transitions: 10000
  sample_iterations: 1

training:
  device: auto
  # EfficientZero V1 Atari batch size.
  batch_size: 256
  unroll_steps: 5

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
